sudo: required
services:
    docker

before_install:
    - docker build -t stwalez/docker-react -f Dockerfile.dev .

script:
    - docker run stwalez/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker_react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-727708957863"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY