sudo: required
services:
    docker

before_install:
    - docker build -t stwalez/docker-react -f Dockerfile.dev .

script:
    - docker run stwalez/docker-react -e CI=true npm run test -- --coverage